### PR TITLE
Upgrade deps

### PR DESCRIPTION
**Pull request by kubukoz**

### CODE REVIEW

**Review by gvolpe — APPROVED** [review]
Thanks! There's no CI configured so there's no way to see if this compiles unless you try it manually.

Have you checked whether it works creating a new project using this updated template?

**Comment by gvolpe** [comment]
@kubukoz ping :smiley:

**Comment by kubukoz** [comment]
I'll try setting up CI :D

**Comment by gvolpe** [comment]
There's also this: https://github.com/arturopala/make-it-g8 I'd like to try it out cause these g8 templates are hard to maintain.

**Comment by kubukoz** [comment]
Just FYI, I'm on it. Trying to get some way of testing :)

**Comment by kubukoz** [comment]
OK, looks like I got it...

**Comment by gvolpe** [comment]
@kubukoz cool! Did you try it locally using `g8`?

**Comment by kubukoz** [comment]
Yep, it worked

**Comment by gvolpe** [comment]
Cool, merging now then :)

I'd love to try this out next: https://github.com/arturopala/make-it-g8

**Pull request merged**
